packages:
  - frontend
  - packages/*

allowBuilds:
  "@fortawesome/fontawesome-free": true
  "@parcel/watcher": true
  core-js: true
  esbuild: true

overrides:
  "postcss": "8.5.8"
engineStrict: true
saveExact: true
savePrefix: ""
