import { Config, CustomThemeColors } from "@monkeytype/schemas/configs";

const obj: Config = {
  theme: "serika_dark",
  themeLight: "serika",
  themeDark: "serika_dark",
  autoSwitchTheme: false,
  customTheme: false,
  customThemeColors: [
    "#323437",
    "#e2b714",
    "#e2b714",
    "#646669",
    "#2c2e31",
    "#d1d0c5",
    "#ca4754",
    "#7e2a33",
    "#ca4754",
    "#7e2a33",
  ] as CustomThemeColors,
  favThemes: [],
  showKeyTips: true,
  smoothCaret: "medium",
  words: 50,
  time: 30,
  mode: "time",
  language: "english",
  fontSize: 2,
  caretStyle: "default",
  flipTestColors: false,
  indicateTypos: "off",
  compositionDisplay: "replace",
  timerStyle: "mini",
  liveSpeedStyle: "off",
  liveAccStyle: "off",
  liveBurstStyle: "off",
  colorfulMode: false,
  randomTheme: "off",
  timerColor: "main",
  timerOpacity: "1",
  showAllLines: false,
  keymapMode: "off",
  keymapStyle: "staggered",
  keymapLegendStyle: "lowercase",
  keymapLayout: "overrideSync",
  keymapKeys: "minimal",
  keymapSize: 1,
  fontFamily: "Roboto_Mono",
  smoothLineScroll: false,
  alwaysShowDecimalPlaces: false,
  alwaysShowWordsHistory: false,
  singleListCommandLine: "on",
  capsLockWarning: true,
  playSoundOnError: "off",
  playSoundOnClick: "off",
  soundVolume: 0.5,
  startGraphsAtZero: true,
  showOutOfFocusWarning: true,
  accountChart: ["on", "on", "on", "on"],
  highlightMode: "letter",
  typedEffect: "keep",
  typingSpeedUnit: "wpm",
  ads: "result",
  monkey: false,
  resultSaving: true,
  customBackground: "",
  customBackgroundSize: "cover",
  customBackgroundFilter: [0, 1, 1, 1],
  monkeyPowerLevel: "off",
  burstHeatmap: false,
  showAverage: "off",
  showPb: false,
  tapeMode: "off",
  tapeMargin: 50,
  maxLineWidth: 0,
  playTimeWarning: "off",
};

export function getDefaultConfig(): Config {
  return structuredClone(obj);
}
